name: flutter_expandable_table
description: A Flutter widget for create an expandable table with header and first column fixed.
version: 2.0.2
repository: https://github.com/rickypid/flutter_expandable_table
issue_tracker: https://github.com/rickypid/flutter_expandable_table/issues

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_scroll_shadow: ^1.2.4
  linked_scroll_controller: ^0.2.0
  provider: ^6.1.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0

flutter:
screenshots:
  - description: 'Expandable Table - screenshot 1'
    path: doc/.media/screenshot.png